# Generated by Django 5.2.1 on 2025-05-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type_menu', models.CharField(choices=[('dejeuner', 'Déjeuner'), ('diner', 'Dîner')], max_length=10)),
            ],
        ),
    ]
